from collections.abc import Callable, Iterable
from typing import Any, NoReturn

from ._core import Link
from ._ops import _Generator

async def _await_run(
  result: Any, chain: Chain | None = ..., link: Link | None = ..., root_link: Link | None = ...
) -> Any: ...
def _fire_and_forget(
  result: Any,
  chain: Chain,
  link: Link,
  root_link: Link | None,
  handler_name: str,
  source_exc: BaseException | None,
) -> Any: ...
def _except_handler_body(
  exc: BaseException, chain: Chain, link: Link, root_link: Link | None, root_value: Any
) -> Any: ...
def _finally_handler_body(chain: Chain, root_value: Any, root_link: Link | None) -> Any: ...
def _init_attempt_links(
  chain: Chain,
  has_run_value: bool,
  v: Any,
  args: tuple[Any, ...] | None,
  kwargs: dict[str, Any] | None,
) -> tuple[Link | None, Link | None]: ...
def _stamp_exception_source(exc: BaseException, link: Link | None, current_value: Any) -> None: ...

class Chain:
  _is_chain: bool
  __slots__: tuple[str, ...]
  _retry_backoff: Callable[[int], float] | float | None
  _retry_max_attempts: int | None
  _retry_on: tuple[type[BaseException], ...] | None
  current_link: Link | None
  first_link: Link | None
  is_nested: bool
  on_except_exceptions: tuple[type[BaseException], ...] | None
  on_except_link: Link | None
  on_except_raise: bool
  on_finally_link: Link | None
  root_link: Link | None
  def __init__(self, v: Any = ..., /, *args: Any, **kwargs: Any) -> None: ...
  def _then(self, link: Link) -> Chain: ...
  def _run(self, v: Any, args: tuple[Any, ...] | None, kwargs: dict[str, Any] | None) -> Any: ...
  async def _run_async(
    self,
    awaitable: Any,
    link: Link,
    current_value: Any = ...,
    root_value: Any = ...,
    has_root_value: bool = ...,
    root_link: Link | None = ...,
    run_v: Any = ...,
    run_args: tuple[Any, ...] | None = ...,
    run_kwargs: dict[str, Any] | None = ...,
    retry_attempt: int = ...,
  ) -> Any: ...
  def decorator(self) -> Callable[..., Callable[..., Any]]: ...
  def run(self, v: Any = ..., /, *args: Any, **kwargs: Any) -> Any: ...
  def then(self, v: Any, /, *args: Any, **kwargs: Any) -> Chain: ...
  def do(self, fn: Callable[..., Any], /, *args: Any, **kwargs: Any) -> Chain: ...
  def except_(
    self,
    v: Any,
    /,
    *args: Any,
    exceptions: type[BaseException] | Iterable[type[BaseException]] | None = ...,
    raise_: bool = ...,
    **kwargs: Any,
  ) -> Chain: ...
  def finally_(self, v: Any, /, *args: Any, **kwargs: Any) -> Chain: ...
  def retry(
    self,
    max_attempts: int = ...,
    on: tuple[type[BaseException], ...] | type[BaseException] = ...,
    backoff: Callable[[int], float] | float | None = ...,
  ) -> Chain: ...
  def _get_retry_delay(self, attempt: int) -> float: ...
  def iterate(self, fn: Callable[[Any], Any] | None = ...) -> _Generator: ...
  def iterate_do(self, fn: Callable[[Any], Any] | None = ...) -> _Generator: ...
  def map(self, fn: Callable[[Any], Any], /) -> Chain: ...
  def foreach(self, fn: Callable[[Any], Any], /) -> Chain: ...
  def filter(self, fn: Callable[[Any], Any], /) -> Chain: ...
  def gather(self, *fns: Callable[[Any], Any]) -> Chain: ...
  def with_(self, v: Any, /, *args: Any, **kwargs: Any) -> Chain: ...
  def with_do(self, v: Any, /, *args: Any, **kwargs: Any) -> Chain: ...
  def if_(
    self,
    predicate: Callable[..., Any] | None = None,
    *,
    then: Any,
    args: tuple[Any, ...] | None = None,
    kwargs: dict[str, Any] | None = None,
  ) -> Chain: ...
  def else_(self, v: Any, /, *args: Any, **kwargs: Any) -> Chain: ...
  @classmethod
  def return_(cls, v: Any = ..., /, *args: Any, **kwargs: Any) -> NoReturn: ...
  @classmethod
  def break_(cls, v: Any = ..., /, *args: Any, **kwargs: Any) -> NoReturn: ...
  def __call__(self, v: Any = ..., /, *args: Any, **kwargs: Any) -> Any: ...
  def __bool__(self) -> bool: ...
  def __repr__(self) -> str: ...
