from collections.abc import Callable, Iterable
from typing import Any, NoReturn

from ._core import Link
from ._ops import _Generator

async def _await_run(
  result: Any, chain: Chain | None = ..., link: Link | None = ..., root_link: Link | None = ...
) -> Any: ...
def _except_handler_body(exc: BaseException, chain: Chain, link: Link, root_link: Link | None) -> Any: ...
def _finally_handler_body(chain: Chain, root_value: Any, root_link: Link | None) -> Any: ...

class Chain:
  _is_chain: bool
  __slots__: tuple[str, ...]
  current_link: Link | None
  first_link: Link | None
  is_nested: bool
  on_except_exceptions: tuple[type[BaseException], ...] | None
  on_except_link: Link | None
  on_finally_link: Link | None
  root_link: Link | None
  def __init__(self, v: Any = ..., /, *args: Any, **kwargs: Any) -> None: ...
  def _then(self, link: Link) -> Chain: ...
  def _run(self, v: Any, args: tuple[Any, ...] | None, kwargs: dict[str, Any] | None) -> Any: ...
  async def _run_async(
    self,
    awaitable: Any,
    link: Link,
    current_value: Any = ...,
    root_value: Any = ...,
    has_root_value: bool = ...,
    root_link: Link | None = ...,
  ) -> Any: ...
  def decorator(self) -> Callable[..., Callable[..., Any]]: ...
  def run(self, v: Any = ..., /, *args: Any, **kwargs: Any) -> Any: ...
  def then(self, v: Any, /, *args: Any, **kwargs: Any) -> Chain: ...
  def do(self, fn: Any, /, *args: Any, **kwargs: Any) -> Chain: ...
  def except_(
    self,
    fn: Any,
    /,
    *args: Any,
    exceptions: type[BaseException] | Iterable[type[BaseException]] | None = ...,
    **kwargs: Any,
  ) -> Chain: ...
  def finally_(self, fn: Any, /, *args: Any, **kwargs: Any) -> Chain: ...
  def iterate(self, fn: Callable[[Any], Any] | None = ...) -> _Generator: ...
  def iterate_do(self, fn: Callable[[Any], Any] | None = ...) -> _Generator: ...
  def foreach(self, fn: Callable[[Any], Any], /) -> Chain: ...
  def foreach_do(self, fn: Callable[[Any], Any], /) -> Chain: ...
  def filter(self, fn: Callable[[Any], Any], /) -> Chain: ...
  def gather(self, *fns: Callable[[Any], Any]) -> Chain: ...
  def with_(self, fn: Any, /, *args: Any, **kwargs: Any) -> Chain: ...
  def with_do(self, fn: Any, /, *args: Any, **kwargs: Any) -> Chain: ...
  def if_(self, predicate: Callable[..., Any], fn: Any, /, *args: Any, **kwargs: Any) -> Chain: ...
  def else_(self, fn: Any, /, *args: Any, **kwargs: Any) -> Chain: ...
  def freeze(self) -> _FrozenChain: ...
  @classmethod
  def return_(cls, v: Any = ..., /, *args: Any, **kwargs: Any) -> NoReturn: ...
  @classmethod
  def break_(cls, v: Any = ..., /, *args: Any, **kwargs: Any) -> NoReturn: ...
  def __call__(self, v: Any = ..., /, *args: Any, **kwargs: Any) -> Any: ...
  def __bool__(self) -> bool: ...
  def __repr__(self) -> str: ...

class _FrozenChain:
  __slots__: tuple[str, ...]
  _chain: Chain
  def __init__(self, chain: Chain) -> None: ...
  def run(self, v: Any = ..., /, *args: Any, **kwargs: Any) -> Any: ...
  def __call__(self, v: Any = ..., /, *args: Any, **kwargs: Any) -> Any: ...
  def __bool__(self) -> bool: ...
  def __repr__(self) -> str: ...
