from typing import Any

_OP_SYMBOLS: dict[Any, str]

class _XExpr:
  __slots__: tuple[str, ...]
  _ops: tuple[tuple[str, Any], ...]
  def __init__(self, ops: tuple[tuple[str, Any], ...] = ...) -> None: ...
  def _chain(self, op_type: str, op_args: Any) -> _XExpr: ...
  def __call__(self, value: Any) -> Any: ...
  def __getattr__(self, name: str) -> _XAttr: ...
  def __setattr__(self, name: str, value: Any) -> None: ...
  def __getitem__(self, key: Any) -> _XExpr: ...
  def __repr__(self) -> str: ...
  # Arithmetic operators
  def __add__(self, other: Any) -> _XExpr: ...
  def __radd__(self, other: Any) -> _XExpr: ...
  def __sub__(self, other: Any) -> _XExpr: ...
  def __rsub__(self, other: Any) -> _XExpr: ...
  def __mul__(self, other: Any) -> _XExpr: ...
  def __rmul__(self, other: Any) -> _XExpr: ...
  def __truediv__(self, other: Any) -> _XExpr: ...
  def __rtruediv__(self, other: Any) -> _XExpr: ...
  def __floordiv__(self, other: Any) -> _XExpr: ...
  def __rfloordiv__(self, other: Any) -> _XExpr: ...
  def __mod__(self, other: Any) -> _XExpr: ...
  def __rmod__(self, other: Any) -> _XExpr: ...
  def __pow__(self, other: Any) -> _XExpr: ...
  def __rpow__(self, other: Any) -> _XExpr: ...
  # Bitwise operators
  def __and__(self, other: Any) -> _XExpr: ...
  def __rand__(self, other: Any) -> _XExpr: ...
  def __or__(self, other: Any) -> _XExpr: ...
  def __ror__(self, other: Any) -> _XExpr: ...
  def __xor__(self, other: Any) -> _XExpr: ...
  def __rxor__(self, other: Any) -> _XExpr: ...
  def __lshift__(self, other: Any) -> _XExpr: ...
  def __rlshift__(self, other: Any) -> _XExpr: ...
  def __rshift__(self, other: Any) -> _XExpr: ...
  def __rrshift__(self, other: Any) -> _XExpr: ...
  # Comparison operators
  def __eq__(self, other: Any) -> _XExpr: ...  # type: ignore[override]
  def __ne__(self, other: Any) -> _XExpr: ...  # type: ignore[override]
  def __lt__(self, other: Any) -> _XExpr: ...
  def __le__(self, other: Any) -> _XExpr: ...
  def __gt__(self, other: Any) -> _XExpr: ...
  def __ge__(self, other: Any) -> _XExpr: ...
  # Unary operators
  def __neg__(self) -> _XExpr: ...
  def __pos__(self) -> _XExpr: ...
  def __abs__(self) -> _XExpr: ...
  def __invert__(self) -> _XExpr: ...

class _XAttr(_XExpr):
  __slots__: tuple[()]
  def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

X: _XExpr
