from typing import Callable, Any, AsyncIterator, Generator, Self, Type, overload
from quent import ResultOrAwaitable, Null


type FuncT = Callable[..., Any]


class _Generator:
  def __iter__(self) -> Generator[Any, None, None]: ...
  def __aiter__(self) -> AsyncIterator[Any]: ...
  def __call__(self, v: Any = None, *args: Any, **kwargs: Any) -> _Generator: ...


class Chain:
  """Sequential pipeline where each operation receives the result of the previous one.

  Supports transparent sync/async handling, conditional branching, iteration
  operations, exception handling, and pipe syntax.
  """
  def __init__(self, v: Any = None, *args: Any, **kwargs: Any) -> None: ...

  def clone(self) -> Self: ...

  def decorator(self) -> Callable[[FuncT], FuncT]: ...

  def run(self, v: Any = None, *args: Any, **kwargs: Any) -> ResultOrAwaitable: ...

  def freeze(self) -> '_FrozenChain': ...

  @overload
  def then(self, v: Any, *args: Any, **kwargs: Any) -> Self: ...
  @overload
  def then(self, v: Callable[..., Any], *args: Any, **kwargs: Any) -> Self: ...

  def do(self, fn: Callable[..., Any], *args: Any, **kwargs: Any) -> Self: ...

  def except_(
    self, fn: Callable[..., Any], *args: Any,
    exceptions: tuple[Type[BaseException], ...] | Type[BaseException] | None = None, **kwargs: Any
  ) -> Self: ...

  def finally_(self, fn: Callable[..., Any], *args: Any, **kwargs: Any) -> Self: ...

  def iterate(self, fn: Callable[..., Any] | None = None) -> _Generator: ...

  def iterate_do(self, fn: Callable[..., Any] | None = None) -> _Generator: ...

  def foreach(self, fn: Callable[..., Any]) -> Self: ...

  def foreach_do(self, fn: Callable[..., Any]) -> Self: ...

  def filter(self, fn: Callable[..., Any]) -> Self: ...

  def gather(self, *fns: Callable[..., Any]) -> Self: ...

  def with_(self, fn: Callable[..., Any], *args: Any, **kwargs: Any) -> Self: ...

  def with_do(self, fn: Callable[..., Any], *args: Any, **kwargs: Any) -> Self: ...

  @classmethod
  def return_(cls, v: Any = None, *args: Any, **kwargs: Any) -> Any: ...

  @classmethod
  def break_(cls, v: Any = None, *args: Any, **kwargs: Any) -> Any: ...

  def __call__(self, v: Any = None, *args: Any, **kwargs: Any) -> ResultOrAwaitable: ...

  def __bool__(self) -> bool: ...

  def __repr__(self) -> str: ...


class _FrozenChain:
  """Frozen chain with pre-compiled link tuple for optimized evaluation."""
  def __init__(self, chain: Chain) -> None: ...
  def run(self, v: Any = None, *args: Any, **kwargs: Any) -> ResultOrAwaitable: ...
  def __call__(self, v: Any = None, *args: Any, **kwargs: Any) -> ResultOrAwaitable: ...
  def __bool__(self) -> bool: ...
  def __repr__(self) -> str: ...


class Cascade(Chain):
  """Like Chain, but every operation receives the root value instead of the previous result."""
  def __init__(self, v: Any = None, *args: Any, **kwargs: Any) -> None: ...
  def run(self, v: Any = None, *args: Any, **kwargs: Any) -> ResultOrAwaitable: ...


class _DescriptorWrapper:
  def __init__(self, fn: Callable[..., Any]) -> None: ...
  def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
  def __get__(self, obj: Any, objtype: type | None = None) -> Any: ...


class QuentException(Exception):
  """Base exception for quent chain-related errors."""
  ...
