from typing import Callable, Any, AsyncIterator, Generator, Self, Type, overload
from quent import ResultOrAwaitable, Null


type ChainLink[IN, OUT] = Callable[[IN], OUT]
type AnyLink[OUT, IN] = OUT | Callable[[IN], OUT]
type FuncT = Callable[..., Any]


class _Generator:
  def __iter__(self) -> Generator[Any, None, None]: ...
  def __aiter__(self) -> AsyncIterator[Any]: ...
  def __call__(self, v: Any = None, *args: Any, **kwargs: Any) -> ResultOrAwaitable: ...


class Chain:
  """Sequential pipeline where each operation receives the result of the previous one.

  Supports transparent sync/async handling, conditional branching, iteration
  operations, exception handling, and pipe syntax.
  """
  def __init__(self, v: Any = None, *args: Any, **kwargs: Any) -> None: ...

  def config(self, *, autorun: bool | None = None, debug: bool | None = None, async_: bool | None = None) -> Self: ...

  def autorun(self, autorun: bool = True) -> Self: ...

  def set_async(self, enabled: bool = True) -> Self: ...

  def clone(self) -> Self: ...

  def safe_run(self, v: Any = None, *args: Any, **kwargs: Any) -> ResultOrAwaitable: ...

  def with_context(self, **context: Any) -> Self: ...

  @staticmethod
  def get_context() -> dict: ...

  def freeze(self) -> _FrozenChain: ...

  def decorator(self) -> Callable[[FuncT], FuncT]: ...

  def run(self, v: Any = None, *args: Any, **kwargs: Any) -> ResultOrAwaitable: ...

  @overload
  def then(self, v: Any, *args: Any, **kwargs: Any) -> Self: ...
  @overload
  def then(self, v: Callable[..., Any], *args: Any, **kwargs: Any) -> Self: ...

  def do(self, fn: Callable[..., Any], *args: Any, **kwargs: Any) -> Self: ...

  def root(self, fn: Callable[..., Any], *args: Any, **kwargs: Any) -> Self: ...

  def root_do(self, fn: Callable[..., Any], *args: Any, **kwargs: Any) -> Self: ...

  def attr(self, name: str) -> Self: ...

  def attr_fn(self, name: str, *args: Any, **kwargs: Any) -> Self: ...

  def except_(
    self, fn: Callable[..., Any], *args: Any,
    exceptions: tuple[Type[BaseException], ...] | Type[BaseException] | None = None, reraise: bool = True, **kwargs: Any
  ) -> Self: ...

  def suppress(self, *exceptions: Type[BaseException]) -> Self: ...

  def finally_(self, fn: Callable[..., Any], *args: Any, **kwargs: Any) -> Self: ...

  def on_success(self, fn: Callable[..., Any], *args: Any, **kwargs: Any) -> Self: ...

  def while_true(self, fn: Callable[..., Any], *args: Any, max_iterations: int = 0, **kwargs: Any) -> Self: ...

  def iterate(self, fn: Callable[..., Any] | None = None) -> _Generator: ...

  def iterate_do(self, fn: Callable[..., Any] | None = None) -> _Generator: ...

  def foreach(self, fn: Callable[..., Any], with_index: bool = False) -> Self: ...

  def foreach_do(self, fn: Callable[..., Any], with_index: bool = False) -> Self: ...

  def filter(self, fn: Callable[..., Any], *args: Any, **kwargs: Any) -> Self: ...

  def reduce(self, fn: Callable[..., Any], initial: Any = ..., *args: Any, **kwargs: Any) -> Self: ...

  def gather(self, *fns: Callable[..., Any]) -> Self: ...

  def with_(self, fn: Callable[..., Any], *args: Any, **kwargs: Any) -> Self: ...

  def with_do(self, fn: Callable[..., Any], *args: Any, **kwargs: Any) -> Self: ...

  def if_(self, v: Any, *args: Any, **kwargs: Any) -> Self: ...

  def else_(self, v: Any, *args: Any, **kwargs: Any) -> Self: ...

  def if_not(self, v: Any, *args: Any, **kwargs: Any) -> Self: ...

  def if_raise(self, exc: BaseException) -> Self: ...

  def else_raise(self, exc: BaseException) -> Self: ...

  def if_not_raise(self, exc: BaseException) -> Self: ...

  def condition(self, fn: Callable[..., Any], *args: Any, **kwargs: Any) -> Self: ...

  def not_(self) -> Self: ...

  def eq(self, value: Any) -> Self: ...

  def neq(self, value: Any) -> Self: ...

  def is_(self, value: Any) -> Self: ...

  def is_not(self, value: Any) -> Self: ...

  def in_(self, value: Any) -> Self: ...

  def not_in(self, value: Any) -> Self: ...

  def or_(self, value: Any) -> Self: ...

  def pipe(self, other: Any) -> Self: ...

  def isinstance_(self, *types: Type) -> Self: ...

  def sleep(self, delay: float) -> Self: ...

  def raise_(self, exc: BaseException) -> Self: ...

  @classmethod
  def null(cls) -> Null: ...

  @classmethod
  def return_(cls, v: Any = None, *args: Any, **kwargs: Any) -> Any: ...

  @classmethod
  def break_(cls, v: Any = None, *args: Any, **kwargs: Any) -> Any: ...

  @staticmethod
  def compose(*chains: Any) -> Chain: ...

  @overload
  def __or__(self, other: run) -> ResultOrAwaitable: ...
  @overload
  def __or__(self, other: Any) -> Self: ...

  def __or__(self, other: Any) -> Self | ResultOrAwaitable: ...

  def __call__(self, v: Any = None, *args: Any, **kwargs: Any) -> ResultOrAwaitable: ...

  def __bool__(self) -> bool: ...

  def __repr__(self) -> str: ...


class Cascade(Chain):
  """Like Chain, but every operation receives the root value instead of the previous result."""
  def __init__(self, v: Any = None, *args: Any, **kwargs: Any) -> None: ...
  def run(self, v: Any = None, *args: Any, **kwargs: Any) -> ResultOrAwaitable: ...


class ChainAttr(Chain):
  """Chain variant supporting attribute access on the current value via __getattr__."""
  def __getattr__(self, name: str) -> Self: ...

  @overload
  def __call__(self, *args: Any, **kwargs: Any) -> Self: ...
  @overload
  def __call__(self, v: Any = None, *args: Any, **kwargs: Any) -> ResultOrAwaitable: ...


class CascadeAttr(ChainAttr):
  """Cascade variant supporting attribute access on the current value via __getattr__."""
  def __init__(self, v: Any = None, *args: Any, **kwargs: Any) -> None: ...


class _DescriptorWrapper:
  def __init__(self, fn: Callable[..., Any]) -> None: ...
  def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
  def __get__(self, obj: Any, objtype: type | None = None) -> Any: ...


class _FrozenChain:
  """Immutable snapshot of a chain that can be executed repeatedly without mutation."""
  def decorator(self) -> Callable[[FuncT], FuncT]: ...

  def run(self, v: Any = None, *args: Any, **kwargs: Any) -> ResultOrAwaitable: ...

  def __call__(self, v: Any = None, *args: Any, **kwargs: Any) -> ResultOrAwaitable: ...

class run:
  """Pipe syntax terminator: ``Chain(f1) | f2 | run()``."""
  def __init__(self, v: Any = None, *args: Any, **kwargs: Any) -> None: ...
  def __ror__(self, other: Chain) -> ResultOrAwaitable: ...

class QuentException(Exception):
  """Base exception for quent chain-related errors."""
  ...

FrozenChain = _FrozenChain
